Assets/Scenes/Stage1.unity, Assets/Scripts/BreakBlock.cs, Assets/Scripts/MovingBlock.cs, Assets/Scripts/Player.cs, Assets/Scripts/Trap.cs, Assets/Scripts/UpBlock.cs, Assets/Sprites/item/전등불빛.png.meta, ProjectSettings/Physics2DSettings.asset, ProjectSettings/TagManager.asset
현재 적용되어 있는 오브젝트
- 발판, 가시
연필, 볼펜, 지우개는 script 수정 중
=> fix: 전에 작성되어 있던 stript 수정 및 적용

Assets/Prefabs/Character.meta, Assets/Prefabs/Character/Player.meta, Assets/Prefabs/Character/Player/Player.prefab, Assets/Prefabs/Character/Player/Player.prefab.meta, Assets/Prefabs/Character/Player/Player_Jacket+Sungalsses.prefab, Assets/Prefabs/Character/Player/Player_Jacket+Sungalsses.prefab.meta, Assets/Prefabs/Character/Player/Player_Sunglasses.prefab, Assets/Prefabs/Character/Player/Player_Sunglasses.prefab.meta, Assets/Prefabs/Character/Professor.meta, Assets/Prefabs/Character/Professor/Security.prefab, Assets/Prefabs/Character/Professor/Security.prefab.meta, Assets/Prefabs/Character/Student&Employee.meta, Assets/Prefabs/Character/Student&Employee/Cleaner.prefab, Assets/Prefabs/Character/Student&Employee/Cleaner.prefab.meta, Assets/Prefabs/Character/Student&Employee/Security.prefab, Assets/Prefabs/Character/Student&Employee/Security.prefab.meta, Assets/Prefabs/Character/Student&Employee/Student_Apron.prefab, Assets/Prefabs/Character/Student&Employee/Student_Apron.prefab.meta, Assets/Prefabs/Character/Student&Employee/Student_Jacket.prefab, Assets/Prefabs/Character/Student&Employee/Student_Jacket.prefab.meta, Assets/Prefabs/Character/Student&Employee/Student_LabCoat.prefab, Assets/Prefabs/Character/Student&Employee/Student_LabCoat.prefab.meta, Assets/Scenes/Stage1.unity
교수/총장 제외 캐릭터 prefab 생성
*애니메이션은 적용 x
누락된 발판 스프라이트 적용 완료
=> fix: prefab 작업 중

Assets/InputSystem/PlayerControls.inputactions, Assets/Prefabs/Objects/전등.prefab, Assets/Scenes/Stage1.unity, Assets/Scripts/LightTrap.cs, Assets/Scripts/Player.cs, Assets/URP.asset, Assets/URP.asset.meta, Assets/URP_Renderer.asset, Assets/URP_Renderer.asset.meta, Assets/UniversalRenderPipelineGlobalSettings.asset, Assets/UniversalRenderPipelineGlobalSettings.asset.meta, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/GraphicsSettings.asset, ProjectSettings/QualitySettings.asset, ProjectSettings/ShaderGraphSettings.asset, ProjectSettings/URPProjectSettings.asset
=> feat: 전등 작업

Assets/Prefabs/Objects/깨진 고글.prefab, Assets/Prefabs/Objects/깨진 고글.prefab.meta, Assets/Prefabs/Objects/더러운 가방.prefab, Assets/Prefabs/Objects/더러운 가방.prefab.meta, Assets/Prefabs/Objects/더러운 책.prefab, Assets/Prefabs/Objects/더러운 책.prefab.meta, Assets/Prefabs/Objects/마이크.prefab, Assets/Prefabs/Objects/마이크.prefab.meta, Assets/Prefabs/Objects/물병.prefab, Assets/Prefabs/Objects/물병.prefab.meta, Assets/Prefabs/Objects/붓.prefab, Assets/Prefabs/Objects/붓.prefab.meta, Assets/Prefabs/Objects/스포이드.prefab, Assets/Prefabs/Objects/스포이드.prefab.meta
코딩 팀 회의 중 물병 Asset 추가를 위한 commit
=> fix: Prefab 추가 진행

Assets/Scenes/New Stage1.unity
원래 캐비넷에서 아웃라인 들어간 캐비넷으로 수정했구요, 하트, 엎어진 맥콜캔, 쓰레기, 청소카트 추가했습니다.
=> fix: New stage1 에셋 추가 및 변경

Assets/Scenes/Stage1.unity, Assets/Scripts/Player.cs, Assets/Sprites/UI/김민수/Key.png.meta
=> feat: 임시 카메라 동작 추가

Assets/Aniamtion/Walk.anim, Assets/Aniamtion/플레이어1 GFX.controller, Assets/Prefabs/All/Character/Security.prefab, Assets/Scenes/Stage1.unity, Assets/Scripts/Bottle.cs, Assets/Scripts/FlashLight.cs, Assets/Scripts/FlashLight.cs.meta, Assets/Scripts/LightTrap.cs, Assets/Scripts/Player.cs, Assets/Scripts/Trap.cs
Player
dressState 활용해서 애니메이터 적용
기존 walk 애니메이션 수정해서 확인함
Init() 호출 시 coin 및 bottle 효과 초기화
Trap.cs
doRespawn 선택 시 Player.cs의 Dead() 호출
doRegen 선택 시 FadeIn 기능 추가 (떠 있는 에셋)
public변수 damage 추가
bottle.cs
OnTriggerEnter2D로 수정
Security
손전등 추가
FlashLight.cs 추가로 손전등 방향전환
LightTrap.cs 적용
LightTrap.cs
isFlash 변수로 손전등 활용 시 FadeOut 미사용
=> feat: 플레이어, 데미지에셋, 물병, 손전등

Assets/Aniamtion/All/Player/Player_Sunglasses/Player_Sunglasses.controller, Assets/Scenes/Start.unity, Assets/Scripts/GameManager.cs, Assets/Scripts/LightTrap.cs, Assets/Scripts/PlayerCutscene.cs, Assets/Scripts/PlayerCutscene.cs.meta
Start scene UI 구성
PlayerCutscene.cs 추가
게임시작 시, 씬 전환 연출 제작
LightTrap.cs isBackground로 조작 추가
=> feat: Start scene 진행

Assets/Scenes/Start.unity
=> fix: Start scene UI 오류 수정

Assets/Scenes/New Stage1.unity.meta, Assets/Scenes/Stage2.unity
=> fix: 스테이지2 수정

Assets/Prefabs/UI/New UI+GameManager.prefab, Assets/Scenes/UI.unity
스테이지 선택 씬 (UI.scene)
전체 밝기 조절 (URP 적용)
메뉴 아이콘 사이즈 및 위치 조정
New UI+GameManager.prefab
GameOver 텍스트 수정 (GameOver -> GAME OVER)
메뉴 아이콘 사이즈 및 위치 조정
=> fix: 스테이지 선택 씬 및 UI 수정

Assets/Prefabs/UI/New UI+GameManager.prefab, Assets/Scenes/Stage1.unity, Assets/Scenes/Stage2.unity, Assets/Scenes/Stage3.unity, Assets/Scripts/GameManager&UI/GameManager.cs
New UI+GameManager.prefab,
GameManager.cs
제한시간 타이머 색상 수정
게임 오버 글씨 색상 수정
Stage1 scene
문과쪽 의자 스크립트 제거
Stage1, Stage2 scene
스크립트 적용된 엘리베이터(elevator.prefab) 배치
Stage3 scene
빛나는 탈출구(비상구문1.prefab) 배치
=> fix: UI, 의자, 엘리베이터 기능 수정

Assets/Scripts/Player/Player.cs
Player.cs
점프 시 casting하는 Box y축 길이 조정
=> fix: 플레이어 점프 판정 개선

Assets/Prefabs/All/Map Object/Elevator.prefab, Assets/Prefabs/UI/New UI+GameManager.prefab, Assets/Scenes/Stage1.unity, Assets/Scenes/Stage2.unity, Assets/Scripts/Block&Trap&Item/ElevatorHandler.cs
Elevator.prefab
엘베 뒷 sprite 추가
ElevatorHandler.cs
player가 도착하면 엘리베이터의 문이 닫히고 FadeOut으로 씬 전환하는 기능 구현
New UI+GameManager.prefab
FadeOut용의 Panel 추가
Stage1, Stage2
엘베 뒷 삭제
Elevator.prefab 위치 조정
=> feat: 엘리베이터 기능 구현

Assets/Prefabs/All/Player/Player GFX.prefab, Assets/Scenes/Stage1.unity, Assets/Scenes/Stage3.unity
Player GFX.prefab
AudioSource BGM Loop 활성화, PlayOnAwake 비활성화
Stage1, Stage2
player AudioSource 각 stage에 해당하는 BGM 할당
=> fix: BGM 미변경 현상 수정

Assets/Scripts/GameManager&UI/CameraChanger.cs
CameraChanger.cs
Stage1 문과 구간에서 BGM을 3.5초부터 시작하도록 수정
=> fix: Stage1 문과 BGM 시작 수정

Assets/Scenes/Stage1.unity, Assets/Scenes/Stage2.unity, Assets/Scenes/Stage3.unity, Assets/Scripts/GameManager&UI/CameraChanger.cs
- 카메라 전환 범위 추가 분할
- Stage1 3개
- Stage3 5개
- CameraChanger.cs
- 분할된 Confiner에 맞게 코드 수정
=> fix: 카메라 전환 범위 수정

Assets/Scripts/Block&Trap&Item/Item.cs, Assets/Scripts/Player/Player.cs
Player.cs
OnInit 이벤트를 생성
플레이어 사망 시 OnInit을 호출
Itme.cs
Player.cs의 OnInit 이벤트 구독
이벤트 호출 시 오브젝트 활성화
=> fix: 아이템 재생성

Assets/Scripts/Monster/Detection.cs, Assets/Scripts/Monster/NewChasingMonster.cs, Assets/Scripts/Monster/NewChasingMonster.cs.meta, Assets/Scripts/Player/Player.cs
- 총장 움직임 수정
- 총장을 화면 일정 위치에 고정
- 플레이어 움직임에 따라 움직임 모션 출력
- 던지는 모션은 랜덤으로 출력
=> fix: 총장 움직임 수정

Assets/Aniamtion/Stage3/President/President.controller, Assets/Aniamtion/Stage3/President/Throw.anim, Assets/Prefabs/Stage3/Character/President.prefab
NewChasingMonster.cs 적용
애니메이션 출력 수정
=> fix: 총장 움직임 적용

Assets/Prefabs/UI/New UI+GameManager.prefab, Assets/Scenes/Stage1.unity, Assets/Scenes/Stage2.unity, Assets/Scripts/GameManager&UI/GameManager.cs
New UI+GameManager.prefab
타이머, 메뉴 UI Text 해상도 수정
Stage1, Stage2 scene
bgm play on awake 설정
GameManager.cs
메뉴 UI를 사용할 때, 불필요하게 MainCamera 참조하는 것을 삭제
=> fix: Text 해상도 및 메뉴 UI 수정, 스테이지 bgm 시작 설정

Assets/Prefabs/All/Player/Player GFX.prefab, Assets/Scenes/Stage1.unity, Assets/Scenes/Stage2.unity, Assets/Scenes/Stage3.unity, Assets/Scripts/GameManager&UI/CameraChanger.cs, Assets/Scripts/GameManager&UI/GameManager.cs, Assets/Scripts/Player/Player.cs
- 캐릭터 사망 효과음 추가
- 제한시간 10초 전 효과음 추가 -- BGM과 같이 재생
- 게임 오버 효과음 추가
=> feat: 효과음 추가

Assets/Prefabs/All/Platform/노랑발판/노랑발판 200.prefab, Assets/Prefabs/All/Platform/노랑발판/노랑발판_가운데.prefab, Assets/Prefabs/All/Platform/노랑발판/노랑발판_오른쪽.prefab, Assets/Prefabs/All/Platform/노랑발판/노랑발판_왼쪽.prefab, Assets/Prefabs/All/Platform/보라발판/발판(보라).prefab, Assets/Prefabs/All/Platform/주황발판/발판(주황).prefab
=> fix: 발판 색 변경

Assets/Scenes/Ending.unity
카메라가 씬을 제대로 인식하지 못하는 현상이 존재
canvas Render Mode를 'Screen Space - Camera'로 수정하여, 현재 MainCamera를 할당함으로 카메라의 변화에 캔버스가 영향을 받도록 수정
이에 따른 전체적인 비율의 변화(canvas scale, etc..)가 생겨 임의로 수정
크레딧 speed (150->2)
=> fix: 엔딩씬 비율 수정

Assets/Prefabs/All/Character/Cleaner.prefab, Assets/Prefabs/All/Character/Security.prefab, Assets/Prefabs/Stage1/Character/Liberal_Professor.prefab, Assets/Prefabs/Stage1/Character/Student_Jacket.prefab, Assets/Prefabs/Stage2/Character/Science_Professor.prefab, Assets/Prefabs/Stage2/Character/Student_LabCoat.prefab, Assets/Prefabs/Stage3/Character/Entertainment_Professor.prefab, Assets/Prefabs/Stage3/Character/Student_Apron.prefab, Assets/Scripts/GameManager&UI/SelectSceneHandler.cs
SelectSceneHandler.cs
원활한 테스트를 위해 시작 clearState (0->3) 변경
Cleaner.prefab, Security.prefab, Professor.prefab, Student.prefab 교수 등의 움직이는 캐릭터 오브젝트와 접촉 시 점프가 되지 않는 오류 확인
해당 오브젝트들의 Layer를 Platform으로 변경하여 접촉 시 점프를 초기화하도록 수정
=> feat: UT 빌드 세팅

Assets/Scenes/Ending.unity, Assets/Scenes/UI.unity, Assets/Scripts/GameManager&UI/SelectSceneHandler.cs
-엔딩씬 BGM 적용
-스테이지 선택씬 BGM 적용
-스테이지 선택씬 버튼 클릭 시 효과음 적용
=> fix: BGM 및 효과음 수정

Assets/Scenes/Ending.unity
=> fix: Ending씬 수정

Assets/Prefabs/All/Map Object/Elevator.prefab, Assets/Prefabs/Stage3/Map Object/비상구문1.prefab, Assets/Scenes/Ending.unity, Assets/Scenes/Stage1.unity, Assets/Scenes/Stage2.unity, Assets/Scenes/Stage3.unity, Assets/Scripts/Block&Trap&Item/Bottle.cs, Assets/Scripts/Block&Trap&Item/ElevatorHandler.cs, Assets/Scripts/Ending.cs, Assets/Scripts/GameManager&UI/CameraChanger.cs, Assets/Scripts/Player/Player.cs
Elevator.prefab
-AudioSource 'Call Classic Old Lift Elevator Button With Ride 1' 추가
비상구문1.prefab
-AudioSource 'Magic Spell - Sleeping spell 1' 추가
Stage1, Stage2, Stage3
-Elevator와 비상구문에 FadeOut GameObject가 할당되어있지 않아 화면 전환 효과가 없었던 것을 확인하여 이를 수정
ElevatorHandler.cs
-플레이어와 충돌 시 Current Floor BGM과 플레이어 Walk Audio를 끄고, 엘레베이터에 할당된 효과음을 재생
-이를 위해 CameraChanger.cs와 Player.cs의 일부 변수를 public으로 변경
-엘레베이터 효과음이 종료될 때 까지 대기 후, 씬 전환
Ending, Ending.cs
-씬에 'END' 텍스트와 판넬을 추가
-Ending.cs를 기존 credit 오브젝트에서 삭제하고 Canvas에 추가
-credit 로직 변경
-END 텍스트와 판넬 효과 추가
Bottle.cs
-Player.cs의 OnInit에 Bottle_OnInit 이벤트 추가
-호출 시 오브젝트 활성화
=> feat: 엘레베이터(비상구문) 전환 및 효과음 추가, 물병 재생성

Assets/Scenes/Stage1.unity, Assets/Scenes/Stage3.unity
- 계단 카메라 시작 구간을 내려 더 이른 시기에 전환되도록 변경
- 다음 층 시작 구간을 더 앞으로 당겨 더 이른 시기에 전환되도록 변경
=> fix: Stage1, Stage3 카메라 전환 범위 변경

Assets/Scenes/Stage3.unity, Assets/Scripts/Block&Trap&Item/ElevatorHandler.cs, Assets/Scripts/Ending.cs
Stage3
-End Text 추가
ElevatorHandler.cs
-비상구문1.prefab에서 Stage3 씬 전환을 위해 endTxt 추가
-Stage3에서 FadeOut 후 endTxt가 서서히 나타나도록 수정
Ending.cs
-Stage3와 Ending 씬의 전환이 자연스럽게 이루어지도록, Ending 씬에서의 endTxt(endingTxt)를 수정
=> fix: 탈출구 효과음 전환 수정

Assets/Prefabs/All/Platform/보라발판/발판(보라).prefab, Assets/Prefabs/All/Platform/주황발판/발판(주황).prefab
=> fix: 발판 충돌 판정 수정

Assets/Scenes/Stage1.unity, Assets/Scripts/Monster/ThrowingMonster.cs
- 교수 이동 반경 제한이 제대로 동작하지 않아 설정된 이동 반경을 벗어나 이동하는 오류 해결
- coroutine에 있던 해당 기능을 movepattern으로 이동
- Stage1에서 설정된 이동 반경을 벗어나 공중에서 이동하는 교수 오브젝트의 이동 반경 재설정
=> fix: 교수 이동 반경 코드 수정

Assets/Prefabs/UI/New UI+GameManager.prefab, Assets/Scenes/Start.unity, Assets/Scripts/GameManager&UI/GameManager.cs, Assets/Scripts/GameManager&UI/SelectSceneHandler.cs, Assets/Scripts/Player/PlayerCutscene.cs
- Start Scene Exit 버튼 클릭 시 게임이 꺼지도록 수정
- Start Scene 버튼 사운드 추가
- 인게임 메뉴 버튼 사운드 추가
- UI Scene 메뉴 버튼, Game Start 버튼 사운드 추가
=> fix: UI 사운드 추가, Start Exit 수정

Assets/Prefabs/All/Map Object/StartElevator.prefab, Assets/Prefabs/All/Map Object/StartElevator.prefab.meta, Assets/Scenes/Stage2.unity, Assets/Scenes/Stage3.unity, Assets/Scripts/Block&Trap&Item/StartElevator.cs, Assets/Scripts/Block&Trap&Item/StartElevator.cs.meta, Assets/Scripts/GameManager&UI/GameManager.cs
StartElevator.prefab
-기존 스테이지 씬의 엘레베이터 오브젝트를 삭제하고 Elevator.prefab과 동일하게 만든 프리팹을 생성
-Audio Source에 효과음 'Call Classic Old Lift Elevator Button With Ride 1' 추가
Stage2, Stage3
-스테이지 배경 Sorting Order 수정 (-1 -> -5)
-첫 시작 플레이어 위치 엘레베이터 앞으로 조정
-StartElevator.prefab 추가
StartElevator.cs
-엘레베이터가 열렸다가 닫히는 모션 구현
-Player.cs의 isLive를 참조하여 엘레베이터 모션이 완전히 끝난 후 플레이어 이동 가능
-GameManager.cs의 pauseActive를 참조하여 엘레베이터 모션이 완전히 끝난 후 타이머 작동
GameManager.cs
-instance와 pauseActive를 public으로 변경
=> feat: 시작 엘레베이터 모션 추가

Assets/Prefabs/All/Platform/고정발판/고정발판 200.prefab, Assets/Prefabs/All/Platform/노랑발판/노랑발판 200.prefab, Assets/Scenes/Stage1.unity
- 고정 발판 200
- platform effector 2d surface arc 180으로 수정
- 노랑 발판 200
- platform effector 2d surface arc 180으로 수정
- Stage1
- 처음 시작 발판 prefab 수치 변경된 부분 롤백
=> fix: 발판 platform effector 수정

Assets/Scripts/GameManager&UI/SelectSceneHandler.cs
Reverts didwjddyd/LogIN-Adventure#194
=> Revert "fix: 스테이지 선택씬 아이템페이지 클릭 효과음 변경"

Assets/Scripts/Admob.cs, Assets/Scripts/Block&Trap&Item/ElevatorHandler.cs, Assets/Scripts/GameManager&UI/SelectSceneHandler.cs, Assets/Scripts/UnityAdsManager.cs, ProjectSettings/UnityConnectSettings.asset
- google admob, unity ads 통합
- google admob mediation 사용
- 스테이지 클리어 현황 저장되도록 변경
- 스테이지 페이드아웃 및 광고 전환 딜레이 단축
=> feat: ad mediation

Assets/Prefabs/UI/New UI+GameManager.prefab, Assets/Scenes/Credit.unity, Assets/Scenes/Credit.unity.meta, Assets/Scenes/Start.unity, Assets/Scripts/CreditManager.cs, Assets/Scripts/CreditManager.cs.meta, Assets/Scripts/Ending.cs, Assets/Scripts/GameManager&UI/SelectSceneHandler.cs, Assets/Scripts/Player/PlayerCutscene.cs, ProjectSettings/EditorBuildSettings.asset
- 시작화면 → 크레딧 넘어가는 부분 END 문구 없이 바로 시작
- 크레딧 올라가는 속도 조금 빠르게
- 크레딧 화면에 X 버튼 배치
- X 버튼 색상 조정
- 스테이지 선택 화면 아이템 페이지 넘기는 소리 변경
- 시작 화면 크레딧 버튼 색상 변경
- 아이템 페이지 클릭 시 사운드 겹치는 버그 수정
=> fix: bug fix
